# Generated by Django 5.2 on 2025-04-05 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_user_blog_author_alter_blog_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, related_name='viewed_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
